import { Container, Typography } from '@mui/material';
import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout';

const Home: NextPage = () => {

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container>
        <Typography variant="h2" component="h2">
          Home content
        </Typography>
      </Container>
    </Layout>
  )
}

export default Home
