import type { NextPage } from 'next'
import { useTheme } from "next-themes";
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';

const Home: NextPage = () => {
  const {resolvedTheme, setTheme} = useTheme();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Toon Survival
        </h1>

        <Stack spacing={5} direction="column">
          <Button onClick={() => setTheme(resolvedTheme === "light" ? "dark" : "light")}
            color="primary" variant="contained">
              Change theme
          </Button>
        </Stack>
      </main>
    </div>
  )
}

export default Home
