import { Container, Typography, Grid } from '@mui/material';
import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout';
import Image from 'next/image'
import {HeroSection, JoinButton}  from '../styles/Home.styled';

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroSection>
        <Container>
          <Grid container alignItems="center">
            {/* Image for mobile */}
            <Grid item xs={12} md={6} textAlign={"center"} sx={{ display: { xs: 'block', md: 'none', lg: 'none' } }}>
              <Image src="/images/male1_wide.png" alt="Male survival" width="256" height="384" />
            </Grid>
            <Grid item xs={12} md={6} sx={{textAlign: {xs: 'center', md: 'left'}}}>
              <Typography variant="h2" component="h2" sx={{fontSize: {lg: 50, md: 41, xs: 32}}}>
                A new wave of collectibles is about to hit the blockchain.
              </Typography>
              <JoinButton size="large" variant="contained" color="secondary">Join Discord</JoinButton>
            </Grid>

            {/* Image for desktop */}
            <Grid item xs={12} md={6}	textAlign={"center"} sx={{ display: { xs: 'none', md: 'block', lg: 'block' } }}>
              <Image src="/images/male1_wide.png" alt="Male survival" width="384" height="512" />
            </Grid>
          </Grid>
        </Container>
      </HeroSection>
    </Layout>
  )
}

export default Home
